baseURL = "https://staging.kristiansagi.com/"
title = "Kristian Sägi"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = false
 
 [params.label]
  text = "KS"
 

 # ---- Meta / SEO ----
  description = "Technology leader, builder, and quiet operator. Scaling people, product, and purpose."
  keywords = ["Kristian Sägi", "Technology Leader", "CTO", "Quiet Operator"]


[params.profileMode]
enabled = true
subtitle = "Engineering & Technology Leadership | Scaling People, Product & Purpose. Building high-performing teams. Driving clarity. Turning complexity into growth."

# Sub title, not in the original theme
notice = "Open to Director / VP of Engineering & Product Leadership roles (Estonia & EU)"

imageUrl = "kristian-sagi.webp"
# imageTitle = "<title of image as alt>" # optional
imageWidth = 240
imageHeight = 240

# [params.assets]
#  css = ["css/extended/figure.css", "css/extended/custom.css"]

# Buttons (array of tables)
[[params.profileMode.buttons]]
name = "Explore My Track Record"
url = "/work"

[[params.profileMode.buttons]]
name = "Let's Talk"
url = "/contact"

# [[params.profileMode.buttons]]
# name = "Download My Résumé (PDF)"
# url = "Kristian_Sagi_Resume.pdf"

# Social icons (array of tables)
[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/kristiansagi/"

[[params.socialIcons]]
name = "x"
url = "https://x.com/kristiansagi"

[[params.socialIcons]]
name = "facebook"
url = "https://facebook.com/kristiansagi.public"


[menu]
  [[menu.main]]
    name = "My Story"
    url = "/story/"
    weight = 10
  [[menu.main]]
    name = "My Track Record"
    url = "/work/"
    weight = 20
  [[menu.main]]
    name = "Leadership & Impact"
    url = "/leadership/"
    weight = 30
  [[menu.main]]
    name = "Perspectives"
    url = "/blog/"
    weight = 40
  [[menu.main]]
    name = "Résumé"
    url = "/Kristian_Sagi_Resume.pdf"
    weight = 50
    
    

#  [[menu.main]]
#    name = "Contact"
#    url = "/contact/"
#    weight = 50
